
//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:2.0.50727.5448
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompanyAttribute("Uncas")]
[assembly: System.Reflection.AssemblyProductAttribute("Uncas.Core")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright (c) 2012, Ole Lynge Sørensen")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.1.0.146")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.1.0.146 (0b61f030e6f76f9627d302566d667357ce33bc11)")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.1.0.146")]

